#!/usr/bin/env python

import os
import subprocess
import argparse
import shutil
import nibabel as nib
import matplotlib.pyplot as plt



### DEFINE INPUTS ##############################################################
parser = argparse.ArgumentParser(description="Estimate Statistics on Parameter Values with FreeSurfer ROIs")
parser.add_argument("-l", "--denoising", action="store_true", help="Perform LPCA denoising if set. Default=False", default=False)
parser.add_argumetn("-i", "--dwi", type=str, help="Input the Diffusion weighted image to perform registration", default="None")
parser.add_argument("-s", "--t1", type=str, help="FreeSurfer Subject Directory", default="None")
parser.add_argument("-p", "--parameter_maps", type=str, nargs="+", help="Paths to all parameter_maps to be analyzed", default="None")
parser.add_argumetn("-o", "--output", type=str, help="Output Directory", default="None")

args = parser.parse_args()
################################################################################



### ERROR CHECKING #############################################################
################################################################################



### SET UP OUTPUT DIRECTORY ####################################################
if args.output[-1] != '/':
    outpath = args.output + '/'
else:
    outpath = args.output

if args.t1[-1] != '/':
    t1_path = args.t1 + '/'
else:
    t1_path = args.t1

os.makedirs(outpath)
subprocess.call(["mri_convert", (t1_path + "mri/aparc+aseg.mgz"), (outpath + "aparc+aseg.nii")])
subprocess.call(["mri_convert", (t1_path + "mri/orig.mgz"), (outpath + "t1.nii")])
shutil.copyfile(args.dwi, (outpath + "dwi.nii"))

os.chdir(outpath)
################################################################################



# Run BET on T1
subprocess.call(["bet", "t1.nii", "brain.nii", "-f", "0.5"])

# Register dwi to T1
subprocess.call(["epi_reg", "--epi=dwi.nii", "--t1=t1.nii", "--t1brain=brain.nii", "--out=output"])
