#!/usr/bin/env python

import os
import subprocess
import argparse
import shutil
import matplotlib.pyplot as plt



### DEFINE INPUTS ##############################################################
parser = argparse.ArgumentParser(description="Estimate Statistics on Parameter Values with FreeSurfer ROIs")
parser.add_argument("-i", "--dwi", type=str, help="Input the Diffusion weighted image to perform registration", default="None")
parser.add_argument("-s", "--t1", type=str, help="FreeSurfer Subject Directory", default="None")
parser.add_argument("-p", "--parameter_maps", type=str, nargs="+", help="Paths to all parameter_maps to be analyzed", default="None")
parser.add_argument("-o", "--output", type=str, help="Output Directory", default="None")

args = parser.parse_args()
################################################################################



### ERROR CHECKING #############################################################
################################################################################



### SET UP OUTPUT DIRECTORY ####################################################
if args.output[-1] != '/':
    outpath = args.output + '/'
else:
    outpath = args.output

if args.t1[-1] != '/':
    t1_path = args.t1 + '/'
else:
    t1_path = args.t1

os.makedirs(outpath)
os.environ["FSLOUTPUTTYPE"] = "NIFTI"
subprocess.call(["mri_convert", (t1_path + "mri/aparc+aseg.mgz"), (outpath + "aparc+aseg.nii")])
subprocess.call(["mri_convert", (t1_path + "mri/aparc.a2009s+aseg.mgz"), (outpath + "aparc.a2009s+aseg.nii")])
subprocess.call(["mri_convert", (t1_path + "mri/wmparc.mgz"), (outpath + "wmparc.nii")])
subprocess.call(["mri_convert", (t1_path + "mri/orig.mgz"), (outpath + "t1.nii")])
shutil.copyfile(args.dwi, (outpath + "dwi.nii"))

os.chdir(outpath)
################################################################################


### REGISTER DWI TO T1 #########################################################
# Run BET on T1
subprocess.call(["bet", "t1.nii", "brain.nii", "-f", "0.5"])

# Register dwi to T1
subprocess.call(["epi_reg", "--epi=dwi.nii", "--t1=t1.nii", "--t1brain=brain.nii", "--out=b02t1"])

# Apply Transformation to all parameter maps
for param_map in args.parameter_maps:
    subprocess.call(["flirt", "-interp", "spline", "-in", param_map, "-ref", "t1.nii", "-applyxfm", "-init", "dwi2t1.mat", "-out", param_map + "_reg"])
################################################################################



### PEROFM ROI ANALYSIS FOR ALL PARAMETER MAPS #################################
for param_map in args.parameter_maps:
    calc_roi_stats((param_map + "_reg.nii"), args.t1)
################################################################################

### CLEAN UP EXTRA FILES #######################################################

################################################################################
print args.parameter_maps
