#!/usr/bin/env python

import sys
import math

b = float(sys.argv[1])
littleDelta = float(sys.argv[2])
bigDelta = float(sys.argv[3])
timeStep = 10
if len(sys.argv) > 4:
    timeStep = int(sys.argv[4])
# inputs
#
# b: b value, units of s/mm^2
# littleDelta: little delta (gradient pulse width), units of microseconds
# bigDelta: big delta (pulse separation), units of microseconds
#
# *** Note that the current implementation of diffsim assumes that big
#     delta is the time from the end of the first pulse to the start
#     of the second pulse. The usual definition is that big delta is
#     the time from the start of the first pulse to the start of the
#     second pulse.
#
#     To make life easier for me, this script will assume that the
#     input big delta is defined according to convention, but it will
#     output simulations with big delta redefined to match what
#     diffsim assumes.
#
#     This adjustment should be removed if diffsim is ever changed to
#     use the conventional definition of big delta.

gSquared = 26752.0 * 26752.0 # (gamma is in rad/G/s)

# returns gradient strength in G/cm, which is what diffsim expects
gradientStrength = math.sqrt(1.0e20 * b/(gSquared * littleDelta * littleDelta * (bigDelta - littleDelta/3.0)))



standardValues = '''# Generated by the script generate-sc-simulations.py
#
# These parameters give a b value of %0.2f s/mm^2
#
Delta = %d  # in microseconds (Delta - delta using standard definitions)
delta = %d  # in microseconds
mixing time = 0 # in microseconds (only for DPFG pulses)
gradient strength = %f  # in G/cm
ramp = 0  # in microseconds (for both leading and trailing edges)
pulse = 1  # 0 = gradient echo; 1 = spin echo; 2 = DPFG
periodic = 0  # NOT periodic boundary conditions
snr = 100  # signal-to-noise ratio (percent)
voxel size = 10  # in microns
cylinder array = 0  # periodic array
three region = 0  # core-sheath-bath like in Sen-Basser paper
permeable = 0  # default is permeable = 1
gradient directions = 2  #for newer versions
ntess = 0  # for older versions

#
# Parameters to match Sen-Basser (2005)
#
core radius = 5.0  # in microns
cylinder height = 440  # in microns
x dim = 10.0  # in microns
y dim = 10.0  # in microns
z dim = 400.0  # in microns

nstep = 1  # number of steps (not used)
step size = %d  # time step length in microseconds
nparts = 500000  # number of diffusing molecules
structure file = ../z-cylinder-radius-1-c.mdl  # mcell file describing geometry
signal file = signal-sc.txt # output file for signal amplitude
complex signal file = complex-sc.txt # output file for complex signal data
'''

f = open('sc.txt', 'w')
f.write(standardValues % (b, bigDelta - littleDelta, littleDelta, gradientStrength, timeStep))
f.close()

