#! /usr/bin/env python

import os
import subprocess
import argparse
import shutil
import scipy.io as sio
import numpy as np
import io_functions.file_finder as file_finder
import diffusion_functions.connectome_functions as connectome_functions
import diffusion_functions.util as util


### DEFINE INPUTS #############################################################
parser = argparse.ArgumentParser(description="Perform Anatomically Constrained Tractography and Connectome Analysis using MRtrix3")
parser.add_argument("-i", "--dwi", type=str, help="Input dMRI", default="None");
parser.add_argument("-b", "--bval", type=str, help="bval file", default="None")
parser.add_argument("-v", "--bvec", type=str, help="bvec file", default="None")
parser.add_argument("-m", "--mask", type=str, help="mask file", default="None")
parser.add_argument("-p", "--parameters", type=str, help="Directory Containing MicroStructural Parameters", default="None")
parser.add_argument("-s", "--t1", type=str, help="FreeSurfer Subject Directory", default="None")
parser.add_argument("-o", "--output", type=str, help="Output Directory", default="None")

args = parser.parse_args()
file_location = os.path.dirname(__file__)
parameter_maps = file_finder.scan_for_nifti(os.path.abspath(args.parameters), [])
###############################################################################



### ERROR CHECKING ############################################################
###############################################################################



### SET UP OUTPUT DIRECTORY ###################################################
if args.output[-1] != '/':
    outpath=args.output + '/'
else:
    outpath = args.output

if args.t1[-1] != '/':
    t1_path = args.t1 + '/'
else:
    t1_path = args.t1

os.makedirs(outpath)
os.environ["FSLOUTPUTTYPE"] = "NIFTI"
subprocess.call(["mri_convert", (t1_path + "mri/orig.mgz"), (outpath + "t1.nii")])
subprocess.call(["mri_convert", (t1_path + "mri/aparc+aseg.mgz"), (outpath + "aparc+aseg.nii")])

# Copy DWI files
shutil.copyfile(args.dwi, (outpath + "dwi.nii"))
shutil.copyfile(args.bval, (outpath + "bval"))
shutil.copyfile(args.bvec, (outpath + "bvec"))
shutil.copyfile(args.mask, (outpath + "mask.nii"))

os.chdir(outpath)
###############################################################################



### REGISTER T1 TO DWI ########################################################
# Run BET on T1
subprocess.call(["bet", "t1.nii", "brain.nii", "-f", "0.5", "-R"])

# Register dwi to T1
subprocess.call(["epi_reg", "--epi=dwi.nii", "--t1=t1.nii", "--t1brain=brain.nii", "--out=dwi2t1"])

# Convert Registration Matrix to MRTrix Format
subprocess.call(["transformconvert", "dwi2t1.mat", "dwi.nii", "t1.nii", "flirt_import", "dwi2t1_mrtrix.txt"])

# Apply Inverse Transform to T1 and Parcellation
subprocess.call(["transformcalc", "dwi2t1_mrtrix.txt", "invert", "t12dwi_mrtrix.txt"])

subprocess.call(["mrtransform", "-linear", "t12dwi_mrtrix.txt", "t1.nii", "t1_reg.mif"])
subprocess.call(["mrtransform", "-interp", "nearest", "-linear", "t12dwi_mrtrix.txt", "aparc+aseg.nii", "aparc+aseg_reg.mif"])
###############################################################################



### CREATE SEGMENTATION MASK ##################################################
subprocess.call(["5ttgen", "freesurfer", "aparc+aseg_reg.mif", "5TT.mif"])
###############################################################################



### CONVERT LABELS ############################################################
LUT_location = file_location + '/config/FreeSurferColorLUT.txt'
convert_table = file_location + '/config/fs_default.txt'
subprocess.call(["labelconvert", "aparc+aseg_reg.mif", LUT_location, convert_table, "nodes.mif"])
###############################################################################



### DWI PROCESSING ############################################################
# Convert to mif
subprocess.call(["mrconvert", "dwi.nii", "-fslgrad", "bvec", "bval", "dwi.mif"])

# Estimate Response Function
subprocess.call(["dwi2response", "msmt_5tt", "dwi.mif", "5TT.mif", "RF_WM.txt", "RF_GM.txt", "RF_CSF.txt", "-voxels", "RF_voxels.mif"])

# Upsample
subprocess.call(["mrresize", "-voxel", "1,1,1", "dwi.mif", "dwi_up.mif"])
subprocess.call(["mrresize", "-interp", "nearest", "-voxel", "1,1,1", "mask.nii", "mask_up.nii"])

while True:
    try:
        os.remove('dwi.nii')
        os.remove('mask.nii')
    except:
        continue
    else:
        break

os.rename("mask_up.nii", "mask.nii")
os.rename("dwi_up.mif", "dwi.mif")

# Estimate FODs
subprocess.call(["dwi2fod", "msmt_csd", "dwi.mif", "RF_WM.txt", "WM_FODs.mif", "RF_GM.txt", "GM.mif", "RF_CSF.txt", "CSF.mif", "-mask", "mask.nii"])

# Tractography
subprocess.call(["tckgen", "WM_FODs.mif", "60M.tck", "-act", "5TT.mif", "-backtrack", "-crop_at_gmwmi", "-seed_dynamic", "WM_FODs.mif", "-maxlength", "250", "-select", "60M", "-cutoff", "0.06"])
subprocess.call(["tcksift", "60M.tck", "WM_FODs.mif", "10M_SIFT.tck", "-act", "5TT.mif", "-term_number", "10M"])
###############################################################################



### CONNECTOME GENERATION ######################################################
subprocess.call(["tck2connectome", "10M_SIFT.tck", "nodes.mif", "connectome.csv", "-out_assignments", "tcklabels.txt"])

# Parse out Tracts between regions
#os.mkdir("Tracts")
#subprocess.call(["connectome2tck", "10M_SIFT.tck", "tcklabels.txt", "Tracts/IsoTracts"])

# Generate Track-wise Parameter Data
#track_files = file_finder.scan_for_tracts(os.path.abspath("Tracts"), [])

#track_values = {}
#for parameter in parameter_maps:
#    track_means = []
#    track_stds = []

#    param_path, param_name = os.path.split(parameter)
#    count = 0.0
#    percent_prev = 0.0

#    for track in track_files:
#        subprocess.call(["tcksample", track, parameter, "Tracts/values.txt", "-force", "-quiet"])
#        mean, std = connectome_functions.track_stats(os.path.abspath("Tracts/values.txt"))

#        track_means.append(mean)
#        track_stds.append(std)

        # Update Progress
#        count += 1.0
#        percent = np.around((count / float(len(track_files)) * 100), decimals = 1)
#        if(percent != percent_prev):
#            util.progress_update(param_name + ": ", percent)
#            percent_prev = percent

#    track_values[param_name[:-4] + "_mean"] = track_means
#    track_values[param_name[:-4] + "_std"] = track_stds

# Save MATLAB File
#sio.savemat("Trackwise_Parameters.mat", track_values)
################################################################################



### CLEAN UP ###################################################################
os.remove("5TT.mif")
os.remove("60M.tck")
os.remove("aparc+aseg.nii")
os.remove("brain.nii")
os.remove("bval")
os.remove("bvec")
os.remove("CSF.mif")
os.remove("dwi.mif")
os.remove("dwi2t1.mat")
os.remove("dwi2t1_fast_wmedge.nii")
os.remove("dwi2t1_fast_wmseg.nii")
os.remove("dwi2t1_init.mat")
os.remove("dwi2t1_mrtrix.txt")
os.remove("GM.mif")
os.remove("mask.nii")
os.remove("RF_CSF.txt")
os.remove("RF_GM.txt")
os.remove("RF_voxels.mif")
os.remove("RF_WM.txt")
os.remove("t1.nii")
os.remove("t12dwi_mrtrix.txt")
#shutil.rmtree("Tracts")
################################################################################
